### ISSUE TITLE
panic with err “unreachable” when compile on i386 architecture，but on amd64 notfound this panic

### ISSUE THREAD

**Issue by IoTServ** [klauspost/reedsolomon#102] opened 2019-05-23 08:38 UTC
https://github.com/klauspost/reedsolomon/blob/a9588190c00b0ccd742218388f6ff68bbad83e5c/galois_noasm.go#L33

only on i386 plateform

**Comment by IoTServ** [comment] 2019-05-23 08:44
only linux386

**Comment by klauspost** [comment] 2019-05-23 10:22
@fwessels Do you have time to look at this?

I suspect we should disable AVX2 on non-AMD64 platforms here: https://github.com/klauspost/reedsolomon/blob/a9588190c00b0ccd742218388f6ff68bbad83e5c/options.go#L34

**Comment by IoTServ** [comment] 2019-05-23 11:24
@klauspost oh，yes.
And I found the library  "github.com/klauspost/cpuid" show the server support cpuid.CPU.AVX512F() , cpuid.CPU.AVX512BW() both GOARCH set 386 and amd64,but anthoer lib "github.com/intel-go/cpuid" said the server not support AVX512 when GOARCH set 386,so I need fork and disable it Manually?thans

**Comment by klauspost** [comment] 2019-05-23 13:03
I think AVX512 is available on i386, so not reporting it would be wrong.

The avx512 code is only made for 64 bits, so the problem is in this package.

**Comment by IoTServ** [comment] 2019-05-23 13:10
@klauspost oh，thanks，maybe I will wait your commit if you have time,that will be great!So I will close this issue.

**Comment by klauspost** [comment] 2019-05-23 15:11
If you don't mind, I would like to keep it open, since it is an issue that should be fixed. Thanks for reporting it!

**Comment by IoTServ** [comment] 2019-05-23 15:12
@klauspost ok

**Closed** 2019-05-26 10:12 UTC

**Comment by klauspost** [comment] 2019-05-26 11:19
v1.9.2 released
