### ISSUE TITLE
Why limiting shards to 257?

### ISSUE THREAD

**Issue by nicola** [klauspost/reedsolomon#78] opened 2018-05-04 12:36 UTC
(as the questions says!)
This should be unbounded, one should be able to pick any size, no?

**Comment by klauspost** [comment] 2018-05-04 12:49
The underlying "gf8" engine only supports matrices up to 256x256. 

PAR2 uses gf16, which allows up to 64k shards, but typically a bit slower. This package currently does not implement gf16.

**Comment by nicola** [comment] 2018-05-04 14:37
Thanks a lot for your reply!
Mind linking PAR2? I wonder if you can support more than that!

**Comment by animetosho** [comment] 2018-05-19 08:45
[PAR2](https://en.wikipedia.org/wiki/Parchive) is more of a file format which *uses* GF( 2^16 ) under the hood, as opposed to some library to help you do RS coding.

If you're looking for a PAR2 implementation in Go, there is [one available here](https://github.com/akalin/gopar). I don't know if there's any library interface, but you could adopt it to your needs perhaps. For other implementations of PAR2, [here's a list of all the PAR2 clients I know of](https://github.com/animetosho/ParPar/blob/master/benchmarks/info.md#applications-tested-and-commands-given). For PAR2 as a library, there's [libpar2](https://github.com/Parchive/libpar2) (based off par2cmdline); [my own PAR2 client](https://github.com/animetosho/ParPar) provides a (mostly undocumented) Node.js API, otherwise I don't actually know of any other library.

If you're looking for RS implementations, there's some listed [on the readme of this project](https://github.com/klauspost/reedsolomon#links), but I think most are GF(256). [GF-Complete](http://lab.jerasure.org/jerasure/gf-complete) is a C library which has a relatively complete implementation, supporting GF( 2^w ) where *w* = {4,8,16,32,64,128}. There's probably many other RS libraries out there (I haven't personally checked) but I doubt any are as feature complete as GF-Complete.

> I wonder if you can support more than that!

As mentioned above, GF-Complete has implementations going up to GF( 2^128 ), which is likely much larger than you'd ever need. Theoretically, you could go further, but do note that performance goes down proportionally, not to mention that performance *also* proportionally decreases the more shards you have (without using FFT techniques).

**Comment by klauspost** [comment] 2018-05-21 17:29
Closing, since this is a duplicate of #72 - thanks for the details animetosho!

**Closed by klauspost** 2018-05-21 17:29 UTC
